Command to open compiled file
rescript-lang/rescript-vscode pull request #294
Opened 2021-08-10 20:26 UTC by fhammerschmidt

This implements #107 

Press CMD+Shift+P and select `ReScript: Open the compiled JS file for this implementation file.`
It should open the corresponding `.bs.js`, `.js`, `.mjs` in the correct directory (whether in-source or not).

Unfortunately, this requires to parse `bsconfig.json`. I did not know how to account for an array with more than one element of package-specs, so for now it just takes the first one, but I guess it is better to use an object anyway, as [suggested by the docs](https://rescript-lang.org/docs/manual/latest/build-configuration#package-specs).

2022-03-01 00:41 UTC, fhammerschmidt commented
Yes! Just did that and also factored out all the commands into separate files.
Bonus: You can open the compiled file both with the CMD+SHIFT+P menu and the following icon in the navigation menu: 
<img width="39" alt="image" src="https://user-images.githubusercontent.com/18074327/156082746-62c15cef-c38e-4a04-b9b8-fb39e2e9e7a5.png">

Let me know if you think there is a better icon for this action: https://code.visualstudio.com/api/references/icons-in-labels#icon-listing

2022-03-01 08:51 UTC, cristianoc commented on server/src/utils.ts
> +  return JSON.parse(bsconfigFile);
How about catching the parse error inside this function. So there's no need to wrap the callers in a try block. Assuming that was the only reason to use a try block in the caller, which I think is true at least for the previous uses of bsconfig parse.

2022-03-02 17:09 UTC, fhammerschmidt commented
IMO yes, I used it all day while working on a big monorepo and it always worked well so far.

2022-03-03 10:14 UTC, cristianoc commented on server/src/constants.ts
> +export let bsconfigModuleDefault = "commonjs";
Tested on the sample project in `analysis/tests`: it fails to find `lib/js/...` as it's looking into `lib/commonjs/...`.
The project's bsconfig does not speicify any of the relevant data, so relies on all the defaults.

2022-03-03 10:15 UTC, cristianoc requested changes
See comments.

2022-03-03 11:48 UTC, fhammerschmidt commented
I tried to be more explicit with the modulename -> foldername resolving. 
Also added another case when you directly set the "package-specs" field to a string.
Tested it with the example project now as well (and I tested all possible module format strings).

2022-03-03 12:58 UTC, cristianoc approved these changes
Fantastic. Merging.

2022-03-03 12:58 UTC, merged