Use a different rescript-editor-analysis.exe when on ARM
rescript-lang/rescript-vscode pull request #428
Opened 2022-05-22 17:49 UTC by ellbur

2022-05-23 04:19 UTC, cristianoc commented
One comment is that this change affects M1 macs, and would need to not change the path in that case. As the installation does not have a `darwin-arm64` folder.

Even for linux arm, there's no automatic installation that creates `linux-arm64` so I'm not sure where that is created.
If you create it yourself manually, why not put the executable simply in `linux`?

2022-05-23 04:20 UTC, cristianoc requested changes

2022-05-23 04:20 UTC, cristianoc commented on server/src/constants.ts
> +let platformArchString = process.platform + archString;
Breaks on Mac m1.

2022-05-23 04:21 UTC, cristianoc commented on server/src/constants.ts
> +let platformArchString = process.platform + archString;
Should be gated to only apply on linux.

2022-05-23 12:08 UTC, ellbur commented
> Even for linux arm, there's no automatic installation that creates `linux-arm64` so I'm not sure where that is created. If you create it yourself manually, why not put the executable simply in `linux`?

Yes, I am creating it myself manually. The issue is that [vim-rescript](https://github.com/rescript-lang/vim-rescript) includes executables in its package, so it needs a way to include a separate executable for ARM.

I will fix it so it only applies to Linux, and test whether code reformatting still works.

2022-06-04 17:51 UTC, ellbur commented
I tested that code formatting does still work (using `:RescriptFormat` in vim-rescript).

2022-06-23 20:30 UTC, cristianoc commented
https://github.com/rescript-lang/rescript-vscode/pull/467

2022-06-23 20:30 UTC, closed without merging