[DRAFT] ReScript Project spec
rescript-lang/rescript-vscode pull request #51
Opened 2020-12-19 09:37 UTC by IwanKaramazow

Formalize the heuristics to detect compiler executables for editor tooling

2020-12-19 09:56 UTC, IwanKaramazow commented
@bobzhang could you give this a review? Editor tooling needs to be able to get this correct for monorepos and normal projects.

2020-12-22 08:11 UTC, bobzhang requested changes
we can schedule a meeting if you find it more efficient

2020-12-22 08:11 UTC, bobzhang commented on PROJECT_HEURISTICS.md
> +
This is not exact since if you are not in the root project but in a dependency, this might be wrong

2020-12-22 08:11 UTC, bobzhang commented on PROJECT_HEURISTICS.md
> +
I have a vague memory that there is something called `path.resolve`

2020-12-22 08:11 UTC, bobzhang commented on PROJECT_HEURISTICS.md
> +- `.compiler.log` is located at `path.join(foundDirectory, "lib", "bs", ".compiler.log")`
this is correct

2020-12-22 08:11 UTC, bobzhang commented on PROJECT_HEURISTICS.md
> +
seems correct

2020-12-22 08:11 UTC, bobzhang commented on PROJECT_HEURISTICS.md
> +
this is incorrect. user should only run bsb in the main repo.
The project is organised with the assumption that there's only main entry point, user should never run `bsb` in different directories.

2020-12-22 08:11 UTC, bobzhang commented on PROJECT_HEURISTICS.md
> +
This should not happen, since the main entry point decides the compiler version

2020-12-24 05:23 UTC, IwanKaramazow commented
@bobzhang if you have some time, would it be possible to schedule a short meeting to go over my questions and your feedback? It might be faster.

2021-01-06 09:41 UTC, chenglou commented
Superseded by #59 and 5caa099c7d3133fa8e444dd1162388a4c34f6b7b. Closing for now til we reopen this.

2021-01-06 09:41 UTC, closed without merging